{% set name = "napari-pssr" %}
{% set version = "0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-pssr-{{ version }}.tar.gz
  sha256: 5c9681e7f7a35f0d00357fdb33ae08754687b467bbebd43f3787d14e77d67f5c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - bioimageio.core
    - gunpowder
    - magicgui
    - matplotlib-base
    - napari
    - numpy
    - python >=3.7
    - pytorch
    - zarr

test:
  imports:
    - napari_pssr
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pattonw/napari-pssr
  summary: A plugin for training and applying pssr
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - pattonw
